
--Users(uid, email, firstname, lastname, address, password)
CREATE TABLE Users (
    uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

--Account(uid, balance)
CREATE TABLE Account (
    uid INT NOT NULL PRIMARY KEY REFERENCES Users(uid),
    balance FLOAT NOT NULL DEFAULT 0.0 CHECK (balance >= 0.0);
);

--Purchases(uid, oid, time_purchased, total_amount, item_quantity, fulfillment_status, order_page)
CREATE TABLE Purchases (
    oid INT NOT NULL PRIMARY KEY,
    uid INT NOT NULL REFERENCES Users(uid),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    total_amount FLOAT NOT NULL,
    item_quantity INT NOT NULL,
    fulfillment_status VARCHAR(20) NOT NULL CHECK (fulfillment_status IN ('Ordered', 'In Transit', 'Delivered')),
    order_page VARCHAR(2048)
);

--PublicView(uid, firstname, seller, email, address, reviews)
CREATE VIEW PublicView(uid, firstname, email, address, reviews) AS
    SELECT uid, firstname, email, address, reviews
    FROM Users, Seller_Reviews
    WHERE Users.uid = Seller_Reviews.id
;

CREATE TABLE Product_Categories (
    category VARCHAR(255) NOT NULL PRIMARY KEY
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price FLOAT NOT NULL,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE Product_Reviews (
    uid REFERENCES Users(uid),
    pid REFERENCES Products(id),
    time_reviewed timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    rating INT NOT NULL,
    comments VARCHAR(2048),
    votes INT NOT NULL DEFAULT 0,
    PRIMARY KEY (uid, pid)
);

CREATE TABLE Sellers (
    id REFERENCES Users(id),
    PRIMARY KEY (id)
    --seller_name: how to deal with this if sellers are also users
);

CREATE TABLE Inventory (
    seller_id REFERENCES Sellers(id),
    pid REFERENCES Products(id),
    in_stock INT NOT NULL
);

CREATE TABLE Seller_Reviews (
    uid REFERENCES Users(uid),
    seller_id REFERENCES Sellers(id),
    time_reviewed timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    rating INT NOT NULL,
    comments VARCHAR(2048),
    votes INT NOT NULL DEFAULT 0,
    PRIMARY KEY (uid, seller_id)
);

CREATE TABLE Images_Reviews (
    uid REFERENCES Users(uid),
    pid REFERENCES Products(id), 
    img INT NOT NULL
);

CREATE TABLE Cart(
    cid INT NOT NULL PRIMARY KEY
);

CREATE TABLE InCart (
    cid REFERENCES Cart(cid),
    p_quantity INT NOT NULL,
    unit_price REFERENCES Products(price),
    total_price FLOAT NOT NULL,
    pid REFERENCES Products(id),
    uid REFERENCES Users(uid),
    PRIMARY KEY(cid)
);

CREATE TABLE SaveForLater (
    cid REFERENCES Cart(cid),
    p_quantity INT NOT NULL,
    unit_price REFERENCES Products(price),
    total_price FLOAT NOT NULL,
    pid REFERENCES Products(id),
    uid REFERENCES Users(uid),
    PRIMARY KEY(cid)
);

CREATE TABLE Orders (
    cid REFERENCES Cart(cid),
    oid INT NOT NULL,
    order_totalPrice FLOAT NOT NULL,
    fulfilled BOOLEAN DEFAULT FALSE,
    PRIMARY KEY(oid)
);

CREATE TABLE Update_Submission(
    buyer_balance FLOAT NOT NULL,
    seller_balance FLOAT NOT NULL,
    fulfilled_time timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    oid REFERENCES Orders(id),
    cid REFERENCES Cart(cid),
    seller_id REFERENCES Sellers(id),
    bid REFERENCES Buyers(id),
    PRIMARY KEY(oid, seller_id, bid)
);

