-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

--Public(uid, firstname, seller, email, address, reviews)

--Users(uid, email, firstname, lastname, address, password)
CREATE TABLE Users (
    uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

--Account(uid, balance)
CREATE TABLE Account (
    uid NOT NULL PRIMARY KEY REFERENCES Users(uid),
    balance FLOAT NOT NULL
);

--Purchases(uid, oid, time_purchased, total_amount, item_quantity, fulfillment_status, order_page)
CREATE TABLE Purchases (
    oid INT NOT NULL PRIMARY KEY,
    uid NOT NULL REFERENCES Users(uid),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    total_amount FLOAT NOT NULL,
    item_quantity INT NOT NULL,
    fulfillment_status VARCHAR(20) NOT NULL CHECK (fulfillment_status IN ('Ordered', 'In Transit', 'Delivered')),
    order_page VARCHAR(2048)
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price FLOAT NOT NULL,
    available BOOLEAN DEFAULT TRUE
);
